site_name: gitpod-django
site_description: Test
repo_url: https://github.com/jankeromnes/gitpod-django-postgres
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/jankeromnes">jankeromnes</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
